name: Docker image build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build & Push Image
        run: |
          echo ${{ secrets.DOCKERTOKEN }} | docker login -u "aaradhyaag" --password-stdin
          docker build -t aaradhyaag/fastapi-app:latest .
          docker push aaradhyaag/fastapi-app:latest